name: Bash

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubunty-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run bash
        run: bash *.sh
