name: Bash

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run bash
        run: bash *.sh
